### ISSUE TITLE
"Apply transformations to paths" setting isn't shown as checked after reopening

### ISSUE THREAD

**Issue by Vasilich** [RazrFalcon/svgcleaner-gui#11]
Settings - Paths - "Apply transformations to paths" setting isn't shown as checked after reopening the settings dialog- it is always unchecked (though it is written as true in w32 registry settings after saving checked value)

**Comment by RazrFalcon** [comment]
That's a bug. But it's only a viewer bug, so flag is still enabled and you can use it.

Will fix it soon.

**Comment by RazrFalcon** [comment]
Try this one: 
[svgcleaner_win32_0.9.0-r1.zip](https://github.com/RazrFalcon/svgcleaner-gui/files/1067704/svgcleaner_win32_0.9.0-r1.zip)

**Comment by Vasilich** [comment]
fixed in version posted above.
Thank you
