### ISSUE TITLE
check-gcc-output failed with "no-return-in-nonvoid-function" when building rpm

### ISSUE THREAD

**Issue by ghost** [RazrFalcon/svgcleaner-gui#12]
Hi,

When I try to package svgcleaner-gui in .rpm package format (for openSUSE), build is OK but rpm checks failed with the following output:

```[   10s] ... running 02-check-gcc-output
[   10s] ... testing for serious compiler warnings
[   10s]     (using /usr/lib/build/checks-data/check_gcc_output)
[   10s]     (using /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/.build.log)
[   10s] 
[   10s] I: Program returns random data in a function
[   10s] E: svgcleaner no-return-in-nonvoid-function src/exceptions.cpp:37
[   10s] E: svgcleaner no-return-in-nonvoid-function src/process.cpp:77
[   10s] 
[   10s] I: Program returns random data in a function
[   10s] E: svgcleaner no-return-in-nonvoid-function src/exceptions.cpp:37
[   10s] E: svgcleaner no-return-in-nonvoid-function src/process.cpp:77
```
I had to disable those checks to be able to build it correctly.
I guess that's no big deal as the build itself runs fine but this issue can prevent svgcleaner-gui from being build automatically in OBS.

Thank you for your time and attention.
Regards.

**Comment by RazrFalcon** [comment]
Yes. GCC doesn't check `switch` statement.  So it's just a warning. I will fix this warning.

**Comment by ghost** [comment]
Thank you. That's indeed just a warning but openSUSE OBS is very pernickety with checks :)

**Comment by RazrFalcon** [comment]
Done.

**Comment by ghost** [comment]
Thanks a lot, OBS checks are happy now !
And by the way, thanks for this great piece of software which is very useful to a lot of people (archeologists) where I work.

**Comment by RazrFalcon** [comment]
Thanks! Glad it helps.
