### ISSUE TITLE
Tab order in GUI

### ISSUE THREAD

**Issue by edent** [RazrFalcon/svgcleaner-gui#13]
Preferences -> Output

I click my mouse in "coordinates" I then press `tab`.

I expect the cursor to move to the next item "properties", instead it jumps down 3 to "path's coordinates".

My C++ is pretty rusty, but I think the issue is in https://github.com/RazrFalcon/svgcleaner-gui/blob/master/src/preferences/outputpage.ui

I think it's to do with the order in which the XML file is generated (based on https://stackoverflow.com/questions/2823351/how-to-automate-detection-of-out-of-order-tab-navigation-in-qt-dialogs)

**Comment by RazrFalcon** [comment]
Yes, tab order is broken. 

Will fix it soon.
