### ISSUE TITLE
executable not found

### ISSUE THREAD

**Issue by antsher** [RazrFalcon/svgcleaner-gui#15]
When i unpack the archive and try to run svgcleaner-gui, i get the following error:

The '7za' executable is not found.
It should be in the application folder.

But 7za file is located in the application folder and it has executable permissions

**Comment by RazrFalcon** [comment]
I presume you are using Linux.

https://github.com/RazrFalcon/svgcleaner/issues/177 
https://github.com/RazrFalcon/svgcleaner/issues/178

Basically, something broken with the latest updated in linux and 7z stopped working. The current solution is to use the system one.
