### ISSUE TITLE
Some files can't be processed.

### ISSUE THREAD

**Issue by damian101** [RazrFalcon/svgcleaner-gui#16]
I noticed that these two files couldn't be processed (with default settings):
https://upload.wikimedia.org/wikipedia/commons/1/10/Konzept-karte_der_Freien_Software.svg
https://upload.wikimedia.org/wikipedia/commons/1/10/Konzept-karte_der_Freien_Software.svg

**Comment by RazrFalcon** [comment]
Yes. XML namespaces are not supported yet.

Duplicate https://github.com/RazrFalcon/svgcleaner/issues/176
