### ISSUE TITLE
The '7za' executable is not found.  It should be in the application folder.

### ISSUE THREAD

**Issue by kawpii** [RazrFalcon/svgcleaner-gui#21]
**Steps to reproduce**

- Download the svgcleaner_linux_x86_64_0.9.5.tar.gz
- Extract it
- `./svgcleaner-gui`

**Result**

Dialog box with following message The '7za' executable is not found.  It should be in the application folder.

But in the directory there is `7za`, which is provided by the tar ball

**Comment by RazrFalcon** [comment]
#15

**Comment by kawpii** [comment]
Thanks fixed it! Is not it better to use 7za from the global installation
