### ISSUE TITLE
Don't use 7-Zip for macOS releases.

### ISSUE THREAD

**Issue by reitermarkus** [RazrFalcon/svgcleaner-gui#6]
By default, macOS cannot open 7-Zip files, hence it doesn't make sense to provide the macOS release as such.

**Comment by RazrFalcon** [comment]
You mean the installation package or produced svgz files?

Linux also do not support 7z, but it isn't a problem, since you can install it. Also, Keka is very popular among macOS users.

If you want a different archive by default - which one?

I chose 7-Zip, because it has a better compression ratio.

**Comment by reitermarkus** [comment]
> You mean the installation package or produced svgz files?

I mean the installation package.

> Keka is very popular among macOS users.

I'm actually using Keka myself, but since I'm using Homebrew Cask to manage GUI applications, this would add a (unnecessary) dependency on `unar`.

> If you want a different archive by default - which one?

I really don't care about which one exactly, as long it is supported by default. But since you said you chose 7-Zip because it has a better compression ratio, I'd suggest `tar.xz` (~8 MB) if you feel strongly about file size, or otherwise just use `zip` (~10 MB), which is still reasonably small for a GUI application in my opinion.

**Comment by RazrFalcon** [comment]
I'm not a macOS user - so I don't know which archive is supported out of the box. And which one is the 'default'. As far as I know - it's `zip`. Not sure for `tar.xz`.

I think the best option is to provide packages in different archives.

**Comment by reitermarkus** [comment]
Yes, the default surely is `zip` (when you create an archive using Finder), but all archives which can be created with the `tar` command (`tar.gz/tar.bz2/tar.xz/tar.lzma`) are also supported.

**Comment by RazrFalcon** [comment]
OK. I will add it in the next release.

**Comment by reitermarkus** [comment]
Great, thanks! And of course also a big 👍  for this neat program.

**Comment by RazrFalcon** [comment]
Fixed.
