### ISSUE TITLE
xcb plugin?

### ISSUE THREAD

**Issue by edent** [RazrFalcon/svgcleaner-gui#9]
Downloaded the latest Linux release - tried to run the GUI on Ubuntu 14.04.  Received this error message.

```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
```

Which magical `apt-get` commands do I need to invoke to get the GUI working?

**Comment by RazrFalcon** [comment]
Try installing `libxcb-xinerama0`.

**Comment by edent** [comment]
That did the trick - thanks!

**Comment by RazrFalcon** [comment]
Well, I should mention this somewhere...
